name: oslomarka-backend
on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v6

      - name: Build and publish go to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          ENV: prod
        with:
          registry: https://ghcr.io
          name: optimuscrime/oslomarka/oslomarka-go
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: docker_go.Dockerfile
          tags: "latest"
